# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_field: date
  sort_reverse: true

comments: false

webmentions:
  username: tobiasfenster.io

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: "Tech blog by Tobias Fenster"
description: "A tech blog"
keywords: "tech, technology, blog, mvp, cto, docker, container, azure, devops, dynamics, nav, business central, ax, f&0, crm, ce, d365"
url: "https://tobiasfenster.io"
baseurl: ""

google_analytics: UA-150365788-1

# Author settings
author:
  name: Tobias Fenster
  title: "tech blog"
  job: CTO at Cosmo Consult and dual Microsoft MVP
  bio: "I'm a technology enthusiast, working mainly on Microsoft Dynamics 365, Azure and Docker. Always trying to push the boundaries."
  thumb: /images/author.png
  email: tobias.fenster@cosmoconsult.com
  url: https://tobiasfenster.io
  github: https://github.com/tfenster
  twitter: https://twitter.com/tobiasfenster
  linkedin: https://linkedin.com/in/tobiasfenster

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
